language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
install: true
before_script:
  - mvn dependency:tree
after_success:
  - mvn jacoco:report coveralls:report